In [53]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import metrics

In [54]:
data = pd.read_csv('classification.csv')

In [55]:
data.head()

true  pred
0     1     0
1     1     1
2     1     1
3     0     0
4     1     1

In [56]:
data.shape

(200, 2)

In [57]:
# Подсчитайте величины TP, FP, FN и TN согласно их определениям. Например, 
# FP — это количество объектов, имеющих класс 0, но отнесенных алгоритмом к классу 1. 
# Ответ в данном вопросе — четыре числа через пробел.

In [58]:
TP = data[(data['true']==1) & (data['pred']==1)]['true'].value_counts()
FP = data[(data['true']==0) & (data['pred']==1)]['true'].value_counts()
FN = data[(data['true']==1) & (data['pred']==0)]['true'].value_counts()
TN = data[(data['true']==0) & (data['pred']==0)]['true'].value_counts()

In [59]:
TP, FP, FN, TN

(1    43
 Name: true, dtype: int64, 0    34
 Name: true, dtype: int64, 1    59
 Name: true, dtype: int64, 0    64
 Name: true, dtype: int64)

In [60]:
# Посчитайте основные метрики качества классификатора:

# Accuracy (доля верно угаданных) — sklearn.metrics.accuracy_score
# Precision (точность) — sklearn.metrics.precision_score
# Recall (полнота) — sklearn.metrics.recall_score
# F-мера — sklearn.metrics.f1_score
# В качестве ответа укажите эти четыре числа через пробел.

In [61]:
accuracy = sklearn.metrics.accuracy_score

In [62]:
print(np.round(sklearn.metrics.accuracy_score(data['true'], data['pred']),decimals = 2)) 

0.54


In [63]:
print(np.round(sklearn.metrics.precision_score(data['true'], data['pred']),decimals = 2)) 

0.56


In [64]:
print(np.round(sklearn.metrics.recall_score(data['true'], data['pred']),decimals = 2)) 

0.42


In [65]:
print(np.round(sklearn.metrics.f1_score(data['true'], data['pred']),decimals = 2)) 

0.48


In [66]:
a = np.round(sklearn.metrics.accuracy_score(data['true'], data['pred']),decimals = 2)
b = np.round(sklearn.metrics.precision_score(data['true'], data['pred']),decimals = 2)
c = np.round(sklearn.metrics.recall_score(data['true'], data['pred']),decimals = 2)
d = np.round(sklearn.metrics.f1_score(data['true'], data['pred']),decimals = 2)

In [67]:
file = "files_lesson.txt"

In [68]:
myfile = open(file, mode = 'a', encoding = 'utf')

In [69]:
# Имеется четыре обученных классификатора. В файле scores.csv записаны истинные классы и значения степени 
# принадлежности положительному классу для каждого классификатора на некоторой выборке:

# для логистической регрессии — вероятность положительного класса (колонка score_logreg),
# для SVM — отступ от разделяющей поверхности (колонка score_svm),
# для метрического алгоритма — взвешенная сумма классов соседей (колонка score_knn),
# для решающего дерева — доля положительных объектов в листе (колонка score_tree).

In [70]:
data_scores = pd.read_csv('scores.csv')

In [71]:
data_scores.head()

true  score_logreg  score_svm  score_knn  score_tree
0     0      0.683832   0.145976   0.787063    0.500000
1     1      0.801966   0.239511   1.000000    0.833333
2     0      0.382315  -0.245701   0.000000    0.000000
3     1      0.506797  -0.137058   0.000000    0.105263
4     1      0.488781  -0.154148   0.000000    0.105263

In [72]:
logit = sklearn.metrics.roc_auc_score(data_scores['true'], data_scores['score_logreg'])

In [73]:
svm = sklearn.metrics.roc_auc_score(data_scores['true'], data_scores['score_svm'])

In [74]:
knn = sklearn.metrics.roc_auc_score(data_scores['true'], data_scores['score_knn'])

In [75]:
tree = sklearn.metrics.roc_auc_score(data_scores['true'], data_scores['score_tree'])

In [76]:
max(logit, svm, knn, tree)

0.719187675070028

In [77]:
logit

0.719187675070028

In [91]:
precision, recall, thresholds = sklearn.metrics.precision_recall_curve(data_scores['true'], data_scores['score_logreg'])

In [79]:
# Посчитайте площадь под ROC-кривой для каждого классификатора. 
# Какой классификатор имеет наибольшее значение метрики AUC-ROC (укажите название столбца)? 
# Воспользуйтесь функцией sklearn.metrics.roc_auc_score.
# Какой классификатор достигает наибольшей точности (Precision) при полноте (Recall) не менее 70% ?

In [92]:
recall

array([1.        , 0.98979592, 0.97959184, 0.97959184, 0.97959184,
       0.96938776, 0.96938776, 0.95918367, 0.95918367, 0.95918367,
       0.95918367, 0.94897959, 0.93877551, 0.93877551, 0.93877551,
       0.93877551, 0.93877551, 0.93877551, 0.93877551, 0.93877551,
       0.93877551, 0.93877551, 0.93877551, 0.93877551, 0.93877551,
       0.93877551, 0.93877551, 0.92857143, 0.92857143, 0.92857143,
       0.92857143, 0.92857143, 0.92857143, 0.91836735, 0.91836735,
       0.90816327, 0.90816327, 0.90816327, 0.90816327, 0.89795918,
       0.89795918, 0.89795918, 0.8877551 , 0.8877551 , 0.8877551 ,
       0.87755102, 0.87755102, 0.86734694, 0.86734694, 0.86734694,
       0.85714286, 0.85714286, 0.84693878, 0.84693878, 0.84693878,
       0.84693878, 0.83673469, 0.83673469, 0.83673469, 0.82653061,
       0.82653061, 0.82653061, 0.82653061, 0.81632653, 0.81632653,
       0.81632653, 0.80612245, 0.79591837, 0.79591837, 0.79591837,
       0.79591837, 0.78571429, 0.78571429, 0.78571429, 0.78571

In [93]:
arr = []
for index, a in enumerate(recall):
    if a>=0.7:
        arr.append(index)
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85]


In [95]:
precision[0:85]

array([0.49746193, 0.49489796, 0.49230769, 0.49484536, 0.49740933,
       0.49479167, 0.4973822 , 0.49473684, 0.4973545 , 0.5       ,
       0.5026738 , 0.5       , 0.4972973 , 0.5       , 0.50273224,
       0.50549451, 0.50828729, 0.51111111, 0.51396648, 0.51685393,
       0.51977401, 0.52272727, 0.52571429, 0.52873563, 0.53179191,
       0.53488372, 0.5380117 , 0.53529412, 0.53846154, 0.54166667,
       0.54491018, 0.54819277, 0.55151515, 0.54878049, 0.55214724,
       0.54938272, 0.55279503, 0.55625   , 0.55974843, 0.55696203,
       0.56050955, 0.56410256, 0.56129032, 0.56493506, 0.56862745,
       0.56578947, 0.56953642, 0.56666667, 0.5704698 , 0.57432432,
       0.57142857, 0.57534247, 0.57241379, 0.57638889, 0.58041958,
       0.58450704, 0.58156028, 0.58571429, 0.58992806, 0.58695652,
       0.59124088, 0.59558824, 0.6       , 0.59701493, 0.60150376,
       0.60606061, 0.60305344, 0.6       , 0.60465116, 0.609375  ,
       0.61417323, 0.61111111, 0.616     , 0.62096774, 0.62601

In [82]:
max_ = max(precision[0:85])
max_

0.6302521008403361

In [114]:
def max_precision(i):
    precision, recall, thresholds = sklearn.metrics.precision_recall_curve(data_scores['true'], i)
    arr = []
    for index, a in enumerate(recall):
        if a>=0.7:
            arr.append(index)
    arr_min = min(arr)
    arr_max = max(arr)
    max_ = max(precision[arr_min:arr_max])
    return(max_)

In [115]:
print(max_precision(data_scores['score_logreg']))

0.6302521008403361


In [116]:
print(max_precision(data_scores['score_svm']))

0.6228070175438597


In [117]:
print(max_precision(data_scores['score_knn']))

0.6065573770491803


In [118]:
print(max_precision(data_scores['score_tree']))

0.5984848484848485


In [120]:
precision, recall, thresholds = sklearn.metrics.precision_recall_curve(data_scores['true'], data_scores['score_tree'])

In [124]:
recall

array([1.        , 0.93877551, 0.91836735, 0.82653061, 0.80612245,
       0.74489796, 0.66326531, 0.60204082, 0.56122449, 0.42857143,
       0.28571429, 0.18367347, 0.        ])

In [125]:
for i, a in enumerate(recall):
    if a>=0.7:
        print(i)

0
1
2
3
4
5


In [127]:
max(precision[0:5])

0.5984848484848485