In [231]:
# Извлеките из данных признаки и классы. Класс записан в первом столбце (три варианта), признаки — 
# в столбцах со второго по последний.

In [232]:
import pandas as pd
Columns = ['Sort', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 
               'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue',
               'OD280_OD315', 'Roline']
data = pd.read_csv('wine.data', sep=',', names = Columns)

In [233]:
data.head()

Sort  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0     1    14.23        1.71  2.43               15.6        127   
1     1    13.20        1.78  2.14               11.2        100   
2     1    13.16        2.36  2.67               18.6        101   
3     1    14.37        1.95  2.50               16.8        113   
4     1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280_OD315  Roline  
0             5.64  1.04         3.92    1065  
1             4.38  1.05         3.40    1050  
2             5.68  1.03         3.17    1185  
3             7.80  0.86         3.45    1480  
4             4.32  1.04         2.93     735

In [234]:
# Оценку качества необходимо провести методом кросс-валидации по 5 блокам (5-fold). 
# Создайте генератор разбиений, который перемешивает выборку перед формированием блоков (shuffle=True). 
# Для воспроизводимости результата, создавайте генератор KFold с фиксированным параметром random_state=42. 
# В качестве меры качества используйте долю верных ответов (accuracy).

In [235]:
y = data['Sort']
X = data.drop('Sort', axis=1)

In [236]:
# Тестовой простой пример

In [237]:
from sklearn.neighbors import KNeighborsClassifier
first_knn = KNeighborsClassifier()

In [238]:
first_knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [239]:
from sklearn.model_selection import cross_val_score

In [240]:
cross_val_score?

In [241]:
cross_val_score(first_knn, X, y, cv=5)

array([0.7027027 , 0.66666667, 0.63888889, 0.65714286, 0.76470588])

In [242]:
import numpy as np
from sklearn.model_selection import KFold

In [243]:
kf = KFold(n_splits=5, shuffle = True, random_state = 42)

In [244]:
# Найдите точность классификации на кросс-валидации для метода k ближайших соседей 
# (sklearn.neighbors.KNeighborsClassifier), при k от 1 до 50. При каком k получилось оптимальное качество? 
# Чему оно равно (число в интервале от 0 до 1)? Данные результаты и будут ответами на вопросы 1 и 2

In [245]:
from sklearn.neighbors import KNeighborsClassifier

In [246]:
kMeans = []
for k in range(1,51):
    kn = KNeighborsClassifier(n_neighbors=k)
    kn.fit(X, y)
    array = cross_val_score(estimator = kn, X=X, y=y, cv=kf, scoring = 'accuracy')
    m = array.mean()
    kMeans.append(m)
m = max(kMeans)
print(np.round(m,decimals = 2))
s = kMeans.index(m)
print(s+1)

0.73
1


In [247]:
array

array([0.80555556, 0.61111111, 0.72222222, 0.68571429, 0.71428571])

In [248]:
print(kMeans)

[0.7304761904761905, 0.6625396825396825, 0.7082539682539682, 0.6577777777777778, 0.6746031746031746, 0.6742857142857144, 0.68, 0.6799999999999999, 0.7023809523809523, 0.6801587301587302, 0.7025396825396826, 0.6966666666666667, 0.6909523809523809, 0.6793650793650794, 0.701904761904762, 0.6795238095238096, 0.7015873015873015, 0.6795238095238095, 0.6793650793650793, 0.6909523809523809, 0.7019047619047619, 0.6965079365079364, 0.7020634920634921, 0.7076190476190476, 0.7019047619047619, 0.6965079365079365, 0.6963492063492064, 0.7079365079365079, 0.7134920634920634, 0.7079365079365079, 0.690952380952381, 0.7134920634920634, 0.7134920634920634, 0.7246031746031747, 0.7246031746031747, 0.7134920634920636, 0.7134920634920634, 0.7134920634920634, 0.7079365079365079, 0.7077777777777777, 0.7134920634920634, 0.7077777777777777, 0.7077777777777777, 0.7077777777777777, 0.7077777777777777, 0.7077777777777777, 0.6966666666666667, 0.7190476190476192, 0.6966666666666667, 0.7077777777777777]


In [249]:
"""y = data['Sort'].astype(float)
X = data.drop('Sort', axis=1)
X = data.astype(float)"""

"y = data['Sort'].astype(float)\nX = data.drop('Sort', axis=1)\nX = data.astype(float)"

In [250]:
import sklearn as sk

In [ ]:
# Какое оптимальное K получается после нормировки признаков?
# Чему равно максимальное качество после нормировки признаков? 

In [251]:
X_scale = sk.preprocessing.scale(X)
y_scale = y

C:\Users\ivan1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


In [252]:
preprocessing.scale?

In [253]:
X_scale

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [1]:
kf = KFold(n_splits=5, shuffle = True, random_state = 42)

NameError: name 'KFold' is not defined

In [257]:
kMeans = []
for k in range(1, 51):
    kn = KNeighborsClassifier(n_neighbors=k)
    array = cross_val_score(estimator=kn, X=X_scale, y=y, cv=kf, scoring='accuracy')
    m = array.mean()
    kMeans.append(m)   
 
m = max(kMeans)
print(np.round(m,decimals = 2))
s = kMeans.index(m)
print(s+1)

0.98
29


In [256]:
kMeans

[0.943968253968254,
 0.9328571428571429,
 0.9550793650793651,
 0.9382539682539683,
 0.9493650793650794,
 0.9495238095238095,
 0.9495238095238095,
 0.9552380952380952,
 0.9607936507936508,
 0.9607936507936508,
 0.9609523809523809,
 0.9552380952380952,
 0.9495238095238093,
 0.9663492063492063,
 0.9720634920634922,
 0.9720634920634922,
 0.9665079365079364,
 0.9665079365079364,
 0.9553968253968254,
 0.9665079365079364,
 0.9609523809523811,
 0.9665079365079364,
 0.9609523809523809,
 0.9552380952380952,
 0.9552380952380952,
 0.9607936507936508,
 0.9552380952380952,
 0.9663492063492063,
 0.9776190476190475,
 0.9607936507936508,
 0.9552380952380952,
 0.9607936507936508,
 0.9663492063492063,
 0.9663492063492063,
 0.9607936507936508,
 0.9607936507936508,
 0.9552380952380952,
 0.9607936507936508,
 0.9607936507936508,
 0.9607936507936508,
 0.9663492063492063,
 0.9607936507936508,
 0.9663492063492063,
 0.9606349206349206,
 0.9663492063492063,
 0.9495238095238095,
 0.9550793650793651,
 0.94952380952